apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: us.gcr.io/my-kubernetes-project-438008/my-app:staging-20241217070448-ab42385
          ports:
            - containerPort: 8080
