apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app123
  labels:
    app: my-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: us.gcr.io/my-kubernetes-project-438008/my-app:staging-20250107085353-ee9e5b6
          ports:
            - containerPort: 8080
