apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app123
  labels:
    app: my-app
spec:
  replicas: 7
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: us-docker.pkg.dev/my-kubernetes-project-438008/my-app/vector:staging-09-staging-20250220093103-bdfa0cd
          ports:
            - containerPort: 8080
