name: Build and Deploy Docker Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (staging or prod)'
        required: true
        default: 'staging'
      tag:
        description: 'Tag name for the release'
        required: true

jobs:

  deploy:
    permissions:
        id-token: write
        contents: write
  
    runs-on: ubuntu-latest

    env:
      STAGING_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_STAGING }}
      PROD_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_PROD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        id: set-vars
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
            echo "PROJECT_ID=${{ env.STAGING_PROJECT_ID }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo "PROJECT_ID=${{ env.PROD_PROJECT_ID }}" >> $GITHUB_ENV
          else
            echo "Invalid environment: ${{ github.event.inputs.environment }}"
            exit 1
          fi
          echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          # token_format: "access_token"
          workload_identity_provider: "projects/1034644372679/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "gha-pusher@my-kubernetes-project-438008.iam.gserviceaccount.com"

      - name: Configure Docker to Authenticate with GCP
        run: |
          echo "Authenticating Docker with GCP..."
          gcloud auth configure-docker
      - name: Build and push Docker image
        run: |
          IMAGE_NAME="us.gcr.io/${PROJECT_ID}/my-app:${{ github.event.inputs.environment }}-$(date +%Y%m%d%H%M%S)-$(git rev-parse --short HEAD)"
          docker build --build-arg environment=${{ github.event.inputs.environment }} -t "$IMAGE_NAME" .
          docker push "$IMAGE_NAME"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Create a new branch for changes
        run: |
          NEW_BRANCH="${{ github.event.inputs.environment }}-${{ github.event.inputs.tag }}"
          git checkout -b "$NEW_BRANCH"
          echo "Created and switched to branch: $NEW_BRANCH"
          echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV


      - name: Update deployment.yaml
        run: |
          DEPLOYMENT_FILE="k8/${{ github.event.inputs.environment }}/deploy.yaml"
          echo "DEPLOYMENT_FILE=$DEPLOYMENT_FILE" >> $GITHUB_ENV
          sed -i "s|image: us.gcr.io.*my-app:.*|image: ${IMAGE_NAME}|" "$DEPLOYMENT_FILE"
          echo "Updated deployment.yaml with image tag: $IMAGE_NAME"

      - name: Debug File Path
        run: |
          echo "DEPLOYMENT_FILE: $DEPLOYMENT_FILE"
          ls -l $DEPLOYMENT_FILE

      - name: Print Updated Deployment File
        run: |
          echo "Updated deployment file:"
          cat $DEPLOYMENT_FILE


      - name: Commit and Push Changes
        run: |
          git config user.name "git-bot"
          git config user.email "git-bot@gitdomain.com"
      
          # Check if branch exists
          BRANCH_NAME=$NEW_BRANCH
          if git show-ref --verify --quiet refs/heads/"$BRANCH_NAME"; then
            echo "Branch $BRANCH_NAME exists locally. Switching to it..."
            git checkout "$BRANCH_NAME"
          elif git ls-remote --heads origin | grep "refs/heads/$BRANCH_NAME" > /dev/null; then
            echo "Branch $BRANCH_NAME exists remotely. Checking out..."
            git checkout -t origin/"$BRANCH_NAME"
          else
            echo "Branch $BRANCH_NAME does not exist. Creating new branch..."
            git checkout -b "$BRANCH_NAME"
          fi
      
          # Commit changes if there are any
          echo "Staging changes in $DEPLOYMENT_FILE..."
          git add "$DEPLOYMENT_FILE"
          if git diff --cached --exit-code; then
            echo "No changes staged for commit. Exiting."
          else
            echo "Committing changes..."
            git commit -m "Update image tag for $ENVIRONMENT environment to ${IMAGE_NAME}"
            if git ls-remote --heads origin | grep "refs/heads/$BRANCH_NAME" > /dev/null; then
              echo "Pulling the latest changes for branch $BRANCH_NAME..."
              git pull origin "$BRANCH_NAME" --rebase
            fi
            git push origin "$BRANCH_NAME"
            echo "Changes committed and pushed to branch $BRANCH_NAME"
          fi

      - name: Move or Create Tag
        run: |
          TAG_NAME="${{ github.event.inputs.environment }}-${{ github.event.inputs.tag }}"
          echo "Creating or moving tag $TAG_NAME to the latest commit on branch $BRANCH_NAME..."
      
          # Ensure we are on the correct branch
          git checkout "$NEW_BRANCH"
      
          # Create or move the tag
          git tag -f "$TAG_NAME"
          git push origin "$TAG_NAME" --force
          echo "Tag $TAG_NAME moved to the latest commit on branch $BRANCH_NAME"
      
